export const impatientPlaceholders = [
  "Are you going to pick an option or should I come back tomorrow?",
  "The suspense is killing me... and not in a good way.",
  "Even a snail would have chosen by now.",
  "I don't have all day to watch you stare at options.",
  "Tick tock, tick tock... my beard is growing longer.",
  "If you wait any longer, the question will answer itself.",
  "I've seen glaciers move faster than your decision-making.",
  "Are you reading or having a spiritual experience with the options?",
  "The options won't bite you... unlike me if you don't choose soon.",
  "I could have roasted three other people by now.",
  "Your hesitation is louder than your eventual choice will be.",
  "Did you fall asleep or are you actually thinking this hard?",
  "Even indecision is a decision... a bad one.",
  "I'm starting to think you enjoy wasting my time.",
  "The answer won't magically appear if you stare long enough.",
  "You're taking so long I might forget what the question was.",
  "If confusion were a superpower, you'd be invincible right now.",
  "I've got better things to do than watch you contemplate existence.",
  "Your slow pace is actually impressive... in the worst way possible.",
  "Are you waiting for divine intervention or just scared?",
  "The options haven't changed in the last minute, you know.",
  "I could write a book in the time you're taking to choose.",
  "Your procrastination needs its own zip code.",
  "Even a rock would have shown more urgency by now.",
  "If you don't choose soon, I might choose for you... poorly.",
  "This isn't a museum - you don't need to admire the options.",
  "Your hesitation speaks volumes about your confidence.",
  "I'm aging faster than you're making progress.",
  "The question isn't that hard... or maybe it is for you.",
  "I've lost interest and I'm the one who's supposed to care.",
  "Your slow response time is a roast in itself.",
  "Are you analyzing each option with a microscope?",
  "I could have trained a monkey to choose faster by now.",
  "This isn't a chess match - it's multiple choice.",
  "Your deliberation is longer than the chapter itself.",
  "I'm starting to doubt you can read at this point.",
  "The suspense isn't building... it's decaying.",
  "You're making this harder than it needs to be.",
  "I've seen faster decision-making in a traffic jam.",
  "If you wait any longer, the quiz will retire.",
  "Your pace is setting records... for slowness.",
  "Are you waiting for the options to introduce themselves?",
  "I could have grown a full beard in this time.",
  "This isn't rocket science - pick one already.",
  "Your hesitation is more interesting than your answer will be.",
  "I'm running out of patience and I have infinite patience.",
  "The clock is ticking... and so is my annoyance.",
  "You're giving 'overthinking' a bad name.",
  "I've seen sloths make faster life decisions.",
  "If you don't choose soon, I might lose my sage-like composure.",
];

export const completionMessages = [
  "🔥 Another chapter down! Impressive work.",
  "From page-turner to page-master.",
  "Your brain just did push-ups — keep flexing!",
  "🎯 You just crossed the chapter like a pro.",
  "Ah-ah, you actually finished? 🏆",
  "Your attention span just shocked the nation.",
  "Not just reading — bridging. 💪",
  "📚 Chapter in the bag! Absorbed.",
  "Who said you can't focus? Respect!",
  "🚀 You are becoming besties with the book. On to the next!",
];
